server {
    listen 8080;
    client_body_size 6546;
    root ./www;
    index index.html;

    error_page {
        404 error_pages/404.html;
    }

    location /images {
        allow_methods GET DELETE POST        ;
        index maha.html;
        client_body_size 222;
    }
}
